### ISSUE TITLE
automerge not pulling new releases

### ISSUE THREAD

**Issue by leon-thomm** [conda-forge/ryvencore-feedstock#5]
### Comment:

@jan-janssen I reworked large parts of ryvencore over the past few weeks and published 7 alpha releases on ryvencore/main along the way, but I just realized that this repo did not automerge the changes, while ryvencore-qt-feedstock does. I couldn't quickly find the issue myself, maybe you know? Is it because these are alpha releases?

**Comment by jan-janssen** [comment]
The conda version is coupled to the pypi version And the pypi version does not seem to be updated either. Can you update the pypi version? 
https://pypi.org/project/ryvencore/

**Comment by leon-thomm** [comment]
pypi has the new versions, see [releases](https://pypi.org/project/ryvencore/#history), but it shows you only the last *stable* release on https://pypi.org/project/ryvencore/ and the feedstock seems to be pulling only that.
It might be beneficial to also build and publish pre-releases (ryvencore might stay in pre-release for a bit). But if it's not trivial to add this functionality to the feedstock, I currently don't depend on it myself. [docs ref](https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds)

**Comment by jan-janssen** [comment]
From my perspective conda is more for the distribution of stable releases, those who want the latest version can install it themselves. Alternatively, you could also link the recipe directly to your GitHub release.

**Comment by leon-thomm** [comment]
Fair. I'm currently not generating any releases/tags on GitHub, just automatically building a wheel and uploading to PyPI whenever I merge the main branch. But I agree, people can rely on the PyPI release if they want to play around with dev versions.
